"""Shared session state passed through the LangGraph graph."""
from typing import Any, Dict, List, TypedDict


class SessionState(TypedDict, total=False):
    classroom_id: str
    student_id: str
    topic: str

    concept_map: Dict[str, Any]            # Generated by CurriculumMapper
    conversation_history: List[Dict[str, str]]  # [{role: "student"|"examiner", content: str}]

    current_turn: int
    max_turns: int                          # default 8

    fact_check_verdict: Dict[str, Any]      # Latest verdict from FactChecker
    grading_rubric: Dict[str, Any]          # Live scores from Grader
    pedagogical_insight: Dict[str, Any]     # Strategy from pedagogical agent
    final_report: Dict[str, Any]            # Final report (end of session)

    exam_status: str                        # "mapping" | "examining" | "grading_final" | "complete"
    rag_context: List[Dict[str, Any]]       # Relevant RAG chunks for current turn
